### ISSUE TITLE
Error while building  commit #b6a45442f6486dcf8020d30adc5bca68c3d33b09

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#10]
Tried to build from source, at latest commit (b6a45442f6486dcf8020d30adc5bca68c3d33b09) , got this error : 

Sencha Cmd v5.1.3.61
[INF] Processing Build Descriptor : default
[INF] Using GPL Version of Ext JS version 5.1.1.451 from /home/ashok/develop/github/lime2/lime2_dev/ext.
[INF] The implications of using GPL version can be found here (http://www.sencha.com/products/extjs/licensing).
[INF] Loading app json manifest...
[INF] Appending content to /home/ashok/develop/github/lime2/lime2_dev/bootstrap.js
[INF] Writing content to /home/ashok/develop/github/lime2/lime2_dev/bootstrap.json
[INF] Compressing data with YuiJavascriptCompressor
[ERR] C2009: YUI Parse Error (missing name after . operator =>         if (meta.new) {) -- unknown-file:221510:21
[ERR] C2009: YUI Parse Error (syntax error =>             mod.textualChanges().add({) -- unknown-file:221511:17
[ERR] C2009: YUI Parse Error (syntax error =>                 type: 'new',) -- unknown-file:221512:22
[ERR] C2009: YUI Parse Error (syntax error =>                 href: meta['new']) -- unknown-file:221513:22
[ERR] C2009: YUI Parse Error (syntax error =>             });) -- unknown-file:221514:14
[ERR] C2009: YUI Parse Error (missing } after property list =>         if (meta.old) {) -- unknown-file:221516:11
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (meta.old) {) -- unknown-file:221516:23
[ERR] C2009: YUI Parse Error (syntax error =>             mod.textualChanges().add({) -- unknown-file:221517:17
[ERR] C2009: YUI Parse Error (syntax error =>                 type: 'old',) -- unknown-file:221518:22
[ERR] C2009: YUI Parse Error (syntax error =>                 href: meta['old']) -- unknown-file:221519:22
[ERR] C2009: YUI Parse Error (syntax error =>             });) -- unknown-file:221520:14
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:221521:9
[ERR] C2009: YUI Parse Error (syntax error =>         this.setModDataAttributes(node, type);) -- unknown-file:221522:14
[ERR] C2009: YUI Parse Error (invalid return =>         return mod;) -- unknown-file:221523:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221524:5
[ERR] C2009: YUI Parse Error (syntax error =>     activeSubstitutionHandler: function(button, markedElements, originalButton) {) -- unknown-file:221525:31
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (!markedElements.length) {) -- unknown-file:221526:37
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:221528:9
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221532:5
[ERR] C2009: YUI Parse Error (syntax error =>     addActiveSubMeta: function(node) {) -- unknown-file:221533:22
[ERR] C2009: YUI Parse Error (invalid return =>         return this.addActiveMeta(node, 'substitution', meta);) -- unknown-file:221540:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221541:5
[ERR] C2009: YUI Parse Error (syntax error =>     addPassiveMeta: function(node, type, meta) {) -- unknown-file:221542:20
[ERR] C2009: YUI Parse Error (syntax error =>         meta = meta || {};) -- unknown-file:221543:15
[ERR] C2009: YUI Parse Error (invalid return =>         return mod;) -- unknown-file:221559:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221560:5
[ERR] C2009: YUI Parse Error (syntax error =>     activeJoinHandler: function(button, markedElements, originalButton) {) -- unknown-file:221561:23
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (!markedElements.length) {) -- unknown-file:221562:37
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:221564:9
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221568:5
[ERR] C2009: YUI Parse Error (syntax error =>     activeSplitHandler: function(button, markedElements, originalButton) {) -- unknown-file:221569:24
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (!markedElements.length) {) -- unknown-file:221570:37
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:221572:9
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221576:5
[ERR] C2009: YUI Parse Error (syntax error =>     activeRenumberingHandler: function(button, markedElements, originalButton) {) -- unknown-file:221577:30
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (!markedElements.length) {) -- unknown-file:221578:37
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:221580:9
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221583:5
[ERR] C2009: YUI Parse Error (syntax error =>     activeCommonMeta: function(node, type) {) -- unknown-file:221584:22
[ERR] C2009: YUI Parse Error (invalid return =>         return this.addActiveMeta(node, type, meta);) -- unknown-file:221592:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221593:5
[ERR] C2009: YUI Parse Error (syntax error =>     beforeInsertionHandler: function() {) -- unknown-file:221594:28
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221612:5
[ERR] C2009: YUI Parse Error (syntax error =>     insertionHandler: function(button, markedElements) {) -- unknown-file:221613:22
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221628:5
[ERR] C2009: YUI Parse Error (syntax error =>     renumberingHandler: function(button) {) -- unknown-file:221629:24
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221641:5
[ERR] C2009: YUI Parse Error (syntax error =>     splitHandler: function(button) {) -- unknown-file:221642:18
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221722:5
[ERR] C2009: YUI Parse Error (syntax error =>     splitHandlerConsolidation: function(button) {) -- unknown-file:221723:31
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221789:5
[ERR] C2009: YUI Parse Error (syntax error =>     ensureHcontainerNode: function(node) {) -- unknown-file:221790:26
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (!node) {) -- unknown-file:221791:20
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:221793:9
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (!node.classList || !node.classList.contains('hcontainer')) {) -- unknown-file:221794:72
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:221796:9
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221798:5
[ERR] C2009: YUI Parse Error (syntax error =>     getNodeDataFromGrid: function(grid) {) -- unknown-file:221799:25
[ERR] C2009: YUI Parse Error (invalid return =>         return data;) -- unknown-file:221809:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221810:5
[ERR] C2009: YUI Parse Error (syntax error =>     setSplitNodesStyle: function(nodes) {) -- unknown-file:221811:24
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221819:5
[ERR] C2009: YUI Parse Error (syntax error =>     getRadioSelectedValue: function(name) {) -- unknown-file:221820:27
[ERR] C2009: YUI Parse Error (invalid return =>         return (inputItems.length) ? inputItems[0].value : false;) -- unknown-file:221825:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221826:5
[ERR] C2009: YUI Parse Error (syntax error =>     splitElement: function(node, posNode, initialSplitNode) {) -- unknown-file:221827:18
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221869:5
[ERR] C2009: YUI Parse Error (syntax error =>     setSplitMetadataB: function(node1, node2) {) -- unknown-file:221870:23
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221894:5
[ERR] C2009: YUI Parse Error (syntax error =>     setSplitMetadata: function(prevNode, prevMeta, nodes) {) -- unknown-file:221895:22
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:221917:5
[ERR] C2009: YUI Parse Error (syntax error =>     joinHandler: function(button) {) -- unknown-file:221918:17
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222007:5
[ERR] C2009: YUI Parse Error (syntax error =>     joinHandlerConsolidation: function(button) {) -- unknown-file:222008:30
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222102:5
[ERR] C2009: YUI Parse Error (syntax error =>     setJoinMetadata: function(joinedNode, joinedData) {) -- unknown-file:222103:21
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222120:5
[ERR] C2009: YUI Parse Error (syntax error =>     beforeDelHandler: function() {) -- unknown-file:222121:22
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (DocProperties.documentState == 'diffEditingScenarioB') {) -- unknown-file:222122:68
[ERR] C2009: YUI Parse Error (syntax error =>             this.beforeDelHandlerConsolidation();) -- unknown-file:222123:18
[ERR] C2009: YUI Parse Error (syntax error =>         } else {) -- unknown-file:222124:9
[ERR] C2009: YUI Parse Error (syntax error =>             this.beforeDelHandlerAmendment();) -- unknown-file:222125:18
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:222126:9
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222127:6
[ERR] C2009: YUI Parse Error (syntax error =>     beforeDelHandlerConsolidation: function() {) -- unknown-file:222128:35
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222161:5
[ERR] C2009: YUI Parse Error (syntax error =>     beforeDelHandlerAmendment: function() {) -- unknown-file:222162:31
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222190:5
[ERR] C2009: YUI Parse Error (syntax error =>     delHandlerConsolidation: function(removedText, removedNode) {) -- unknown-file:222191:29
[ERR] C2009: YUI Parse Error (invalid return =>             return;) -- unknown-file:222194:19
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222219:5
[ERR] C2009: YUI Parse Error (syntax error =>     addDelMeta: function(node, oldText) {) -- unknown-file:222220:16
[ERR] C2009: YUI Parse Error (invalid return =>         return this.addPassiveMeta(node, 'repeal', meta);) -- unknown-file:222235:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222236:5
[ERR] C2009: YUI Parse Error (syntax error =>     delHandler: function(button, markedElements) {) -- unknown-file:222237:16
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222259:5
[ERR] C2009: YUI Parse Error (syntax error =>     updateSubsMetadata: function(node, oldText) {) -- unknown-file:222260:24
[ERR] C2009: YUI Parse Error (invalid return =>         return this.addPassiveMeta(node, 'substitution', meta);) -- unknown-file:222286:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222287:5
[ERR] C2009: YUI Parse Error (syntax error =>     updateRenumberingMetadata: function(node, oldText, renumberedNode) {) -- unknown-file:222288:31
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222305:5
[ERR] C2009: YUI Parse Error (syntax error =>     beforeSubstitutionHandler: function(aliasButton, elements) {) -- unknown-file:222306:31
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222333:5
[ERR] C2009: YUI Parse Error (syntax error =>     substitutionHandler: function(aliasButton, elements, button) {) -- unknown-file:222334:25
[ERR] C2009: YUI Parse Error (syntax error =>         this.createSubstitution(elements[0]);) -- unknown-file:222335:14
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222336:5
[ERR] C2009: YUI Parse Error (syntax error =>     createRenumbering: function(node, formText, update, renumberedNode) {) -- unknown-file:222337:23
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222372:5
[ERR] C2009: YUI Parse Error (syntax error =>     createSubstitutionBlock: function(node, formText, update, callback) {) -- unknown-file:222373:29
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222435:5
[ERR] C2009: YUI Parse Error (syntax error =>     getNodesGridConfig: function() {) -- unknown-file:222436:24
[ERR] C2009: YUI Parse Error (missing ; before statement =>             store: Ext.create('Ext.data.Store', {) -- unknown-file:222439:19
[ERR] C2009: YUI Parse Error (syntax error =>                 fields: [) -- unknown-file:222440:24
[ERR] C2009: YUI Parse Error (syntax error =>                     'name',) -- unknown-file:222441:27
[ERR] C2009: YUI Parse Error (syntax error =>                     'content',) -- unknown-file:222442:30
[ERR] C2009: YUI Parse Error (syntax error =>                     'id',) -- unknown-file:222443:25
[ERR] C2009: YUI Parse Error (syntax error =>                 ],) -- unknown-file:222445:17
[ERR] C2009: YUI Parse Error (syntax error =>                 data: []) -- unknown-file:222446:22
[ERR] C2009: YUI Parse Error (syntax error =>             }),) -- unknown-file:222447:14
[ERR] C2009: YUI Parse Error (syntax error =>             columns: [) -- unknown-file:222448:21
[ERR] C2009: YUI Parse Error (missing ; before statement =>                     dataIndex: 'name') -- unknown-file:222451:31
[ERR] C2009: YUI Parse Error (syntax error =>                 },) -- unknown-file:222452:18
[ERR] C2009: YUI Parse Error (missing ; before statement =>                     dataIndex: 'content',) -- unknown-file:222455:31
[ERR] C2009: YUI Parse Error (syntax error =>                     flex: 1) -- unknown-file:222456:26
[ERR] C2009: YUI Parse Error (syntax error =>                 },) -- unknown-file:222457:18
[ERR] C2009: YUI Parse Error (missing ; before statement =>                     width: 30,) -- unknown-file:222460:27
[ERR] C2009: YUI Parse Error (syntax error =>                     sortable: false,) -- unknown-file:222461:30
[ERR] C2009: YUI Parse Error (syntax error =>                     menuDisabled: true,) -- unknown-file:222462:34
[ERR] C2009: YUI Parse Error (syntax error =>                     items: [) -- unknown-file:222463:27
[ERR] C2009: YUI Parse Error (missing ; before statement =>                             tooltip: 'Remove',) -- unknown-file:222466:37
[ERR] C2009: YUI Parse Error (syntax error =>                             handler: function(grid, rowIndex) {) -- unknown-file:222467:37
[ERR] C2009: YUI Parse Error (syntax error =>                                 grid.getStore().removeAt(rowIndex);) -- unknown-file:222468:38
[ERR] C2009: YUI Parse Error (syntax error =>                         }) -- unknown-file:222470:25
[ERR] C2009: YUI Parse Error (syntax error =>                 }) -- unknown-file:222472:17
[ERR] C2009: YUI Parse Error (syntax error =>         };) -- unknown-file:222474:9
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222475:5
[ERR] C2009: YUI Parse Error (syntax error =>     createSubstitution: function(node, formText, update) {) -- unknown-file:222476:24
[ERR] C2009: YUI Parse Error (missing ; before statement =>         if (DocProperties.documentState == 'diffEditingScenarioB') {) -- unknown-file:222477:68
[ERR] C2009: YUI Parse Error (syntax error =>             this.createSubstitutionConsolidation(node, update);) -- unknown-file:222478:18
[ERR] C2009: YUI Parse Error (syntax error =>         } else {) -- unknown-file:222479:9
[ERR] C2009: YUI Parse Error (syntax error =>             this.createSubstitutionAmendment(node, formText, update);) -- unknown-file:222480:18
[ERR] C2009: YUI Parse Error (syntax error =>         }) -- unknown-file:222481:9
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222482:6
[ERR] C2009: YUI Parse Error (syntax error =>     createSubstitutionConsolidation: function(node, update) {) -- unknown-file:222483:37
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222495:5
[ERR] C2009: YUI Parse Error (syntax error =>     createSubstitutionAmendment: function(node, oldText, update) {) -- unknown-file:222496:33
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222518:5
[ERR] C2009: YUI Parse Error (syntax error =>     createAndShowFloatingForm: function(node, title, text, readOnly, onAccept, onCancel, customConfig) {) -- unknown-file:222519:31
[ERR] C2009: YUI Parse Error (syntax error =>         customConfig = customConfig || {};) -- unknown-file:222520:23
[ERR] C2009: YUI Parse Error (invalid return =>         return panel;) -- unknown-file:222590:15
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222591:5
[ERR] C2009: YUI Parse Error (syntax error =>     askForRenumbering: function(modEl, textualMod) {) -- unknown-file:222592:23
[ERR] C2009: YUI Parse Error (syntax error =>     },) -- unknown-file:222628:5
[ERR] C2009: YUI Parse Error (syntax error =>     addRenumberingAfterMod: function(modEl, textualMod) {}) -- unknown-file:222629:28
[ERR] C2009: YUI Parse Error (syntax error => }, 0, 0, 0, 0, 0, 0, [) -- unknown-file:222630:2
[ERR] C2009: YUI Parse Error (syntax error =>     AknModsMarker,) -- unknown-file:222631:18
[ERR] C2009: YUI Parse Error (syntax error => ], 0));) -- unknown-file:222633:1
[ERR] C2009: YUI Parse Error (Compilation produced 157 syntax errors. => null) -- unknown-file:2
[ERR] 
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.ExBuild: Failed to compress input
[ERR] ption: Compilation produced 157 syntax errors.
[ERR]

**Comment by kohsah** [comment]
Note:  I used the workspace provided on the build page.

**Comment by obujor** [comment]
This was fixed in the [122018d](https://github.com/cirsfid-unibo/lime/commit/122018da7e98a5aef18440f114c547939765a7f3) commit. 
Synchronize your local repository and try again, it should work.

**Comment by kohsah** [comment]
Super .. that was indeed the problem, Thanks
