### ISSUE TITLE
Outline does not get refreshed if the document changes

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#15]
If I add and delete a container in the document, the outline on the left does not get refreshed. 

See screenshot, there is no hcontainer in the document, but the outline still shows it : 
![screenshot from 2016-03-02 15 53 04](https://cloud.githubusercontent.com/assets/5685392/13457577/042029f6-e08f-11e5-8e07-32ec344d8e69.png)

**Comment by obujor** [comment]
The proper way to remove _marked_ elements is to unmark them, and the Outline will be refreshed. To unmark an element open the context menu by right click and then choose "Unmark" and the type of the unmark. 
![lime - language independent markup editor 2016-03-02 11-55-26](https://cloud.githubusercontent.com/assets/3893568/13458511/ea679fce-e06d-11e5-9581-2ca900633342.jpeg)

**Comment by kohsah** [comment]
Thanks @obujor thats clear now
