### ISSUE TITLE
Getting stuck on "Loading document"

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#19]
I synced my repository with cirsfid-unibo/lime to get the latest updates. 

After this update, LIME seems to get stuck after the login screen : 
![screenshot from 2016-03-04 14 40 53](https://cloud.githubusercontent.com/assets/5685392/13522740/5b48a8aa-e217-11e5-9ea9-f0c151db3850.png)

**Comment by kohsah** [comment]
Maybe the server component has changed ? My server component (lime-server) is the one from the downloaded zip file

**Comment by obujor** [comment]
Server has not changed, we have worked on metadata.
Try to open a web console (in Chrome is Ctrl + Shift + J) to see what is the error.

**Comment by kohsah** [comment]
This is the error showing up in the console : 

TypeError: Ext.getStore(...).getMainDocument(...) is null
http://localhost/lime2dev/packages/akn-mods-marker/src/Controller.js?_dc=1457086401728
Line 465

**Comment by kohsah** [comment]
Looks like the metadata store isnt getting created

**Comment by kohsah** [comment]
I just did a fresh checkout directly from cirsfid-unibo/lime instead of my fork, and I am getting the same error there.

**Comment by obujor** [comment]
Yes, i think the opened file is missing the 'meta' tag or something like that. However, LIME should not  block in these situations, I will fix this.
For now you can reset the opened file by typing in the web console 
`User.setPreference('lastOpened', '')`
 and reload LIME and it should open the welcome dialog without any file in the editor.

**Comment by kohsah** [comment]
Ah I see, indeed the file in the editor does not have any metadata, for some reason that didnt get saved.  so the meta block is empty

**Comment by kohsah** [comment]
OK resetting the user preference works. The marking menu doesn't load initially and throws an exception, but thats fine because the editor doesn't yet know what the doctype is.

**Comment by kohsah** [comment]
I think this problem is as a result of Issue #21 , as the metadata is not getting generated.

**Comment by obujor** [comment]
It should be fixed in the [2e58c46](https://github.com/cirsfid-unibo/lime/commit/2e58c46864bf39c73939b0be1d41c2e494316812) commit, check it out.
