### ISSUE TITLE
Tabs vs spaces

### ISSUE THREAD

**Issue by longhotsummer** [cirsfid-unibo/lime#2]
The code looks like it mixes tabs and spaces, which can be confusing. It would be great to choose one over the other and use it consistently throughout. I suggest spaces and not tabs. Most Javascript, HTML and CSS development uses spaces these days, not tabs.

**Comment by obujor** [comment]
Dear longhotsummer, thanks for your report. We have recently changed the IDE and this was the source of the issue. We will fix the problem as soon as possible after (April 8th).

**Comment by longhotsummer** [comment]
Great, thanks!
