### ISSUE TITLE
widget types - dynamic items in selection list

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#20]
I noticed there is a widget type "list" in which we can specify static values. 
Actually found `widgetTypePatterns` in lime-core/Statics. 

Does the system 'list' widget support loading data from a dynamic data source ?

**Comment by obujor** [comment]
Dynamic data source in widget list is not supported, but you can create a custom widget (AKA contextPanel) in the code not in json files (like [this one](https://github.com/cirsfid-unibo/lime/blob/lime2/packages/akn-metadata/src/tagAttributes/) for references). 
With custom widgets you can implement dynamic data sources and other features supported by ExtJS.

**Comment by kohsah** [comment]
Ah exactly what i need ... thanks for pointing me to the example
