### ISSUE TITLE
Importing a debateReport throws up "invalid doctype debateReport" 

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#24]
There is a check for doc-type in akn-main/src/Uri.js which does not check against the full list of supported AN doc-types. It checks only for 'act', 'bill', 'doc', 'debaterecord', 'documentCollection'

**Comment by kohsah** [comment]
Sent a pull request to fix this

**Comment by obujor** [comment]
Merged the pull request, thaks!
