### ISSUE TITLE
Metadata block XML generation

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#27]
There are a couple of issues here :

1) How to set the name Attribute for FRBRdate ? 

2) The part name is defaulted as "main", and it gets duplicated  e.g. `/akn/ke/bill/2016-03-11/33/main/main`

```

 <FRBRWork>
                    <FRBRthis value="/akn/ke/bill/2016-03-11/33/main/main"/>
                    <FRBRuri value="/akn/ke/bill/2016-03-11/33/main"/>
                    <FRBRdate date="2016-03-11" name=""/>
                    <FRBRauthor href="#" as="#"/>
                    <FRBRcountry value="ke"/>
                </FRBRWork>
                <FRBRExpression>
                    <FRBRthis value="/akn/ke/bill/2016-03-11/33/eng@/main/main"/>
                    <FRBRuri value="/akn/ke/bill/2016-03-11/33/eng@/main"/>
                    <FRBRdate date="" name=""/>
                    <FRBRauthor href="#" as="#"/>
                    <FRBRlanguage language="eng"/>
                </FRBRExpression>
                <FRBRManifestation>
                    <FRBRthis value="/akn/ke/bill/2016-03-11/33/eng@/main.xml/main"/>
                    <FRBRuri value="/akn/ke/bill/2016-03-11/33/eng@/main.xml"/>
                    <FRBRdate date="2016-03-11" name=""/>
                    <FRBRauthor href="#" as="#"/>
                </FRBRManifestation>

```

**Comment by kohsah** [comment]
Found in akn-main XmlSerializer .. the template has no setter for the FRBRdate name. 

The part name is embedded in the template, i suspect its being set already in uri.work / uri.expression and its gets doubled when the template is applied.

**Comment by obujor** [comment]
1) For metadata is used AknMain.metadata.HtmlSerializer, and there is no name for FRBRdate, is set to empty, for now there is no possibility to insert the name value. The date name should be added to the Document model and after to the template and to the interface.

2) Yes it is embedded in the template AknMain.metadata.HtmlSerializer that was just for distinguish the FRBRthis from FRBRuri, this is to be fixed.

**Comment by kohsah** [comment]
Cool thanks - i can try to fix these.

**Comment by kohsah** [comment]
Hi, I have fixed item 2) the FRBRthis FRBRuri problem with pull request #30

**Comment by obujor** [comment]
Thanks, I merged the pull request.
