### ISSUE TITLE
PDF generation error 

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#28]
I get this error trying to generate PDF files , I have abiword running, I have the limeserver running : 

![pdf-error](https://cloud.githubusercontent.com/assets/5685392/13699027/d99dbd86-e79d-11e5-8728-f73085018e91.png)

**Comment by obujor** [comment]
Check if the requested url is correct and if the file is existing in the tmp folder.

**Comment by kohsah** [comment]
Thanks, found the problem. The file is indeed being generated, I had not set SERVER_NAME correctly in lime-config.php. 

Setting SERVER_NAME to the web-root of the lime client fixed it.
