### ISSUE TITLE
Invalid US-ASCII character \xE2  with ruby 2.2.1 , Use of En Dash

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#29]
I have 2 different deployments, one is on ruby 2.1.5 , the other is a new installation on ruby 2.2.1 (always on Ubuntu 14.04). 

With ruby 2.1.5 build is fine, lime works fine. 
With ruby 2.2.1 the build goes through fine, but when I browse the lime page i get the following error : 

Invalid US-ASCII character \xE2  

The error is traced back to line 7 in AknTabVisulaizer.sass (AknVisualizerComponent.scss) ... its basically en-dash symbol between the name in the scss file : 

```
* Monica Palmirani – CIRSFID of the University of Bologna
                   ^^
```

En-Dash is part of the extended ascii character set . I  propose replacing this with ascii double dashes since literal en-dash shows up oddly in the browser and throws up strange errors, since its not really meant to be part of source code. 

The other way is to set the default external encoding in config.rb to UTF-8. but perhaps just replacing the instances of en-dash in code with plain dash (or double dash -- ) should be better.

**Comment by obujor** [comment]
Yes, I think is better to replace the en-dash with a plain dash, only in files which cause this error. 
I don't have ruby 2.2.1 installed so if you want to replace the invalid characters and see if this fixes the error it would be great.
Thanks

**Comment by kohsah** [comment]
Thanks @obujor , I will do this, seems to be complain about 1 file at the moment.
