### ISSUE TITLE
PDF generation does not work on Windows 

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#32]
I am getting an "Impossible to generate PDF" error on Windows installation of lime (it works fine on Linux). 

I have set the AbiWord path in two places : 

lime-config.php : 

```
define('ABIWORD_PATH', 'd:\\apps\\AbiWord\\bin\\AbiWord.exe');
```

and in lime-server/documentsdb/config.json:

```
    "abiword": {
        "path": "/usr/bin/abiword",
        "pathWin": "D:\\apps\\AbiWord\\bin\\AbiWord.exe"
    }
```

**Comment by obujor** [comment]
I confirm that AbiWord some times doesn't work properly on Windows, you can try to do the conversion manually from the promt (to check if this is a problem of AbiWord) like that:
`AbiWord.exe --to=pdf file.html -o file.pdf`

**Comment by kohsah** [comment]
OK thanks will check and confirm

**Comment by obujor** [comment]
AbiWord is no longer used for PDF generation see dde4b41d259ad982d334f810311699efaec86db3 and 752beca266a8107be3fc7ea1928a2afd3bbb8ce1
