### ISSUE TITLE
Lime2 under https ?

### ISSUE THREAD

**Issue by kintarooe79** [cirsfid-unibo/lime#38]
It's possible to run Lime2 Under https ?
I try to change in config files every http request in https, but client don't authenticate

**Comment by obujor** [comment]
It could work under https but we haven't tested it under https yet, maybe there're some things to change in lime-server to support https users authentication.
What is the error (look in the browser console) that you see when you try to authenticate?
Update: [lime-server](https://github.com/cirsfid-unibo/lime-server) doesn't support https yet, this is to be done in the near future.

**Comment by kintarooe79** [comment]
Ok. I suppose the issue was in the lime-server . thanks

**Comment by kohsah** [comment]
@kintarooe79 I have run it under https sometime back. The only config change to make in LIME is in lime-config.php

```
// the server url 
define('SERVER_NAME', 'http://localhost');
```

you need to set that URL to the server https URL ... I am assuming you have done all the other web server configuration required.

**Comment by obujor** [comment]
@kohsah I think that was in LIME 1, now the users authentication is made in lime-server which doesn't support https yet.

**Comment by kohsah** [comment]
@obujor Indeed it was with LIME 1. But what if you run lime-server behind a  nginx reverse proxy  and enable https on the proxy ( i am doing that already but without https ) ..perhaps that should work out of the box ?  you would just need to ensure lime-server is listening only on localhost

**Comment by obujor** [comment]
@kohsah This is a good idea to do a nginx reverse proxy with https enabled, it is to be tested, I think it should work.

**Comment by kintarooe79** [comment]
Hi. the error the client console return on authentication is Cross Origin Request Blocked - 
"the Same origin policy disallows reading the remote resources at https://localhost:9006/documentsdb/users "
 On Web server the Cross Site is allowed 
"Access-Control-Allow-Origin" => "*""

Edit:
On server Side, in Server.js, i have started the listener in https on port 9006

**Comment by kohsah** [comment]
@kintarooe79 is your client being accessed from a different url ? (i.e. not http://localhost... ) 

Note: just saw your update with the server being on https ... in that case even the client needs to be on https ... otherwise you will get the cross origin request blocked

**Comment by obujor** [comment]
This issue was moved to cirsfid-unibo/lime-server#1
