### ISSUE TITLE
Amendments in LIME

### ISSUE THREAD

**Issue by kohsah** [cirsfid-unibo/lime#39]
This is a follow-on to Issue  #31 . I want to have live Amendments - where inserted text in a block appears with an underline and deleted text appears with a strike through - or when a whole block is deleted it appears with a strike through. 

I saw an example of this in the consultation process demo which seems to be a plugin on Lime. Is this something that can be provided in the github repo. Will be happy to extend / contribute to it.

**Comment by obujor** [comment]
Do you have any screenshot of this plugin? I would like to understand exactly what plugin you have seen.

**Comment by kohsah** [comment]
Here is the screenshot : 
![image](https://cloud.githubusercontent.com/assets/5685392/14555189/ca50429a-030e-11e6-904d-9f65eb79ebd5.png)

**Comment by obujor** [comment]
This plugin is a prototype and it requires a server side service to work, it's very custom for that particular case so for now it is not suitable for this repository.
