### ISSUE TITLE
AKN 2.0 support

### ISSUE THREAD

**Issue by longhotsummer** [cirsfid-unibo/lime#5]
We're using AKN 2.0 while 3.0 is still being worked on. Do you have a language plugin for AKN 2.0 or thoughts on how we could easily build that?

**Comment by palmirani** [comment]
Lime permits to use AKN 2.0. There is a plugin for the XML transformation. However all the other plugin like consolidation, diff, visualization, etc. work with AKN 3.0. You must customize them for AKN 2.0. We strongly suggest you to use AKN 3.0 as OASIS standard candidate: 
**\* Documentation of the Akoma Ntoso Vocabulary
https://lists.oasis-open.org/archives/legaldocml/201409/msg00007/akn-core-v1.0-csd01-part1-vocabulary-2014-09-05WD10.doc
**\* Akoma Ntoso Naming Convention
https://lists.oasis-open.org/archives/legaldocml/201409/msg00007/Akoma_Ntoso_Naming_Convention_Version-2014-07-30-wd13.doc
**\* Schema
https://lists.oasis-open.org/archives/legaldocml/201406/msg00009/Release_20140623.zip 

AKN 3.0 is better, it is bugs free, it is in line with the AKN naming convention of IDs.

**Comment by longhotsummer** [comment]
Thanks @palmirani. We're going to stick with AKN 2.0 for now because we can't build against a standard that is still undergoing major changes, such as element names changing completely. Hopefully AKN 3.0 is standardised soon and then we can migrate.

We will look at adjusting the AKN3.0 code to support AKN2.0. I'll post back here as we progress.

**Comment by longhotsummer** [comment]
Do you have scripts to generate the various JSON descriptions of the schemas? That would be very useful.

**Comment by kohsah** [comment]
@longhotsummer you could use Jackson to generate that (http://wiki.fasterxml.com/JacksonJsonSchemaGeneration), but to do that you will need the JAXB annotated class of the schema. I have the JAXB annotated classes for AN 2.0 and AN 3.0 in a library (see https://github.com/kohsah/akomantoso-lib), though I have never really used the 2.0 rendering of the classes myself.

**Comment by palmirani** [comment]
@longhotsummer we have the plug-in for AKN 2.0. We can show you how to us it. However some functionalities are not possible using AKN 2.0. Example: to track the renumbering properly the sections, chapters, etc., to fragment the documents in different XML <portion>, to manage the <documentCollection> in complete way, etc. So the transformation from AKN 3.0 to AKN 2.0 is not a simply readjusting of the FRBR or the xml declaration, and the transformation to AKN 2.0 some time imposes to loose some information captured by the editor LIME (e.g. the wID).

**Comment by longhotsummer** [comment]
@palmirani it would be very useful to see the AKN 2.0 plugin. I know that we won't be able to do some things and we're okay with that. I also realise that it's more complicated than just changing a namespace, I'm happy to work to make those changes.

My big concern is that we can't build a system that creates documents that will not correctly adhere to the standard in a matter of months. With each new release of the AKN 3.0 draft we'll have to change tools and documents, which isn't sustainable.

**Comment by obujor** [comment]
I close this issue since now AKN 3.0 it's stable, indeed it was [approved ](https://www.oasis-open.org/news/announcements/committee-specifications-for-akoma-ntoso-v1-0-and-akoma-ntoso-naming-convention-v) by the members of the OASIS LegalDocumentML (LegalDocML) TC.
