### ISSUE TITLE
Unable to import document

### ISSUE THREAD

**Issue by carmasjr29** [cirsfid-unibo/lime#66]
Hello, I've tried to run a local instance of the LIME editor. I've basically followed the instructions on the "get started" guide for LIME 2.1 and downloaded the LIME-2.1-build-2017-05-19.zip file (I'm on Ubuntu 16.04).
When I select the import option and pick a docx file, what I see in the editor is just a single line... whereas if I import the same file on the online demo, the whole text get imported. 
So I assume it's something that is not working on my local instance, is there a way to debug or find a log file to understand what's going on?

**Comment by obujor** [comment]
Hi!
Could you please upload a screenshot of the result?
In order to debug you can open browser's web console and see if there're some errors.
Have you installed [Abiword](http://www.abiword.org/)?

**Comment by carmasjr29** [comment]
I'm going to try later to capture and upload a screenshot.
Meanwhile, I can tell that I've installed everything on the guide (and their dependencies).
I have eXist-db 3.6.1, mongoDB 3.6.2, java8, abiword 3.0.2, nodejs 8.x, php 7.0.22.
I tried with different versions like php 5.6.33, nodejs 6.0.0 (version 0.10.48 gives compilation errors) but all with no success. Are there specific packages to install?
Also, if I run abiword from command line to convert docx to html, it just works and creates the .html file as expected...
Thank you for any help you could provide

**Comment by obujor** [comment]
Php and Nodejs versions are ok, 5.6 and 0.10 are the minimum, you can install a newer version.
The problem could be abiword version, I'll check the last version and let you know, we are using Abiword 2.8.2.

**Comment by carmasjr29** [comment]
Here's a screenshot... no errors in the console (apart from the 404 "not found" on first open). The violation warnings are meaningless, I saw them appear while I was dragging to resize the console...
![lime](https://user-images.githubusercontent.com/35920305/35567829-b21060f4-05c6-11e8-973e-8e295b4bfd3c.png)

**Comment by obujor** [comment]
Could you try with 2.8.2 Abiword version? For now we cannot use the last version of Abiword because binaries for Windows are missing.

**Comment by carmasjr29** [comment]
I'm trying but I feel I miss something, I had to recompile abiword 2.8.2 from sources (hard word) but when I finally got it working, it fails loading the same file that the newest version imported. I think I have to get the hands on it a little longer... any ways you could try with a more recent version meanwhile?

![abiword](https://user-images.githubusercontent.com/35920305/35578157-8cda4ef4-05e3-11e8-99eb-064ea8ff8a3f.png)

**Comment by carmasjr29** [comment]
Sorry my fault, I forgot to include abiword plugin folder to library path. 
Indeed the problem was the lastest version of abiword, since with 2.8.2 it is now correctly importing the document.

We can close this issue for now. 
Any chances you could look up what's wrong with the last version of Abiword?

Thanks.

**Comment by obujor** [comment]
I hope we'll fix it soon, I opened an [issue](https://github.com/cirsfid-unibo/lime-server/issues/6) in lime-server for this purpose. If you want to help we can fix it sooner.
