### ISSUE TITLE
http://localhost:9006/xml/XsltTransform: Cannot GET /xml/XsltTransform

### ISSUE THREAD

**Issue by eltorre** [cirsfid-unibo/lime#70]
I built lime using the instructions provided in docs/build.md, using the stated versions, but for

- php: using 7.0 instead 5.3
- node: using 8.0 instead 0.10

It seems that I can't save files, nor see the Akoma Ntoso preview for them.

I have found two different errors that might be the source of this behaviour:

- Just after opening the document editor, 
```XML Parsing Error: undefined entity
Location: http://localhost:8008/#
Line Number 1, Column 7:
```

and
```XML Parsing Error: syntax error
Location: http://localhost:8008/#
Line Number 1, Column 1:
```

- When I access `http://localhost:9006/xml/XsltTransform`, I get 

```Cannot GET /xml/XsltTransform```

I think the proper behaviour should be accessing to `lime-server/xml/services/XsltTransform.js`, but no error appears on the console.

Thanks a lot.

**Comment by obujor** [comment]
The result of `http://localhost:9006/xml/XsltTransform` is correct because this service doesn't implement the GET method.
Which version of LIME are you using? The development one (serving the root of the project) or the build (serving this folder "build/production/LIME/")? If you are using the root, after every build you have to run this command `sencha app refresh`.
Can you paste the errors you see in the console?

**Comment by eltorre** [comment]
I am running the one in build/production/LIME (/var/www/html is a symlink to this folder). Should I be serving the other one?

Running `sencha app refresh` in the root gives the following output
```
sencha app refresh
Sencha Cmd v5.1.3.61
[INF] Processing Build Descriptor : default
[INF] Installing dependencies
[INF]      [exec] npm WARN lime-scripts-dev@0.0.1 No repository field.
[INF] Building and injection of LIME config into app.json
[INF] development
[INF] Loading app json manifest...
[INF] Appending content to /home/eltorre/lime/bootstrap.js
[INF] Writing content to /home/eltorre/lime/bootstrap.json
[INF] Restoring original app.json
```

Same output if I run it in build/production/LIME.

Edit:

If you mean the errors when I open Lime on a browser, 

```
XML Parsing Error: undefined entity
Location: http://localhost:8008/
Line Number 1, Column 7:
```

```
XML Parsing Error: syntax error
Location: http://localhost:8008/
Line Number 1, Column 1:
```

**Comment by obujor** [comment]
If you want to edit LIME you should serve the root folder instead of "build/production/LIME" and you don't have to run the build every time you edit something.

It's working now? Can you paste the error you get when you open LIME?

**Comment by eltorre** [comment]
Serving the root instead, I get

```
limeConfig was not found in Ext.manifest. Make sure you successfully executed "sencha app refresh" or "sencha app build" command before using LIME.
```

and 5 instances of 

```
[E] [Ext.Loader] Some requested files failed to load.
```

**Comment by obujor** [comment]
Could you check if the "languagesPlugins/akoma3.0" folder is empty? If so, you didn't download submodules, when cloning the repository you have to run `git clone --recursive`.

**Comment by eltorre** [comment]
```
ls languagesPlugins/akoma3.0/
AknAttributesNormalizer.xsl  LICENSE	localeXsl	styles
AknToXhtml.xsl		     README.md	scripts
HtmlToAkn.xsl		     interface	structure.json
```

**Comment by obujor** [comment]
Could you paste your `config.json` file and the folder from which you are running `sencha app refresh`?

**Comment by eltorre** [comment]
```
ls
Readme.md      bootstrap.json  dev-scripts	 lib	   resources
app.js	       build	       docs		 licences  sass
app.json       build.xml       ext		 lime	   scripts
bootstrap.css  config	       index.html	 packages  test
bootstrap.js   config.json     languagesPlugins  php	   test.html
```

```cat config.json 
{
    "languages": [{"name":"akoma3.0"}],
    "fieldsDefaults": {
        "docLocale": "it"
    },
    "server": {
        "node": "http://localhost:9006"
    }
}
```
browsing localhost:9006 returns

```Cannot GET /```

**Comment by obujor** [comment]
It seams to be ok, could you paste the size of `bootstrap.json` and the output of `lime-server`?

**Comment by eltorre** [comment]
Bootstrap.json is 179Kb.

The output of lime-server is
```
libxml validation: enabled
libxml XSLT: enabled
Listening on port 9006
Connected to MongoDb server  mongodb://mongodb-for-lime:27017/documentsdb
Saxon XSLT: enabled
```

**Comment by obujor** [comment]
This seems to be ok too, could you search for "limeConfig" inside bootstrap.json? If yes, try to open again lime without using browser-cache or empty the cache.

**Comment by eltorre** [comment]
Yes, limeConfig is in bootstrap.json.

After emptying the cache, I can get to the editor. I managed to create some documents, save them and see the XML and PDF outputs for them. Still, I found a strange error.

I added a time to a version, and immediately got the following error in the console:

```
XML Parsing Error: syntax error
Location: http://localhost:9006/documentsdb/Documents/d@d.com/eu/statement/Me/2018-06-07/1123/ady@2018-06-10:00:05/?_dc=1528383468180&page=1&start=0&limit=25
Line Number 1, Column 1:
```

After that, I could no longer save any file, nor open files, nor see the XML output, and the following error appears constantly in the console:

``` [E] Document not translated
XSLT conversion failed languagesPlugins/akoma3.0/HtmlToAkn.xsl,languagesPlugins/akoma3.0/AknAttributesNormalizer.xsl[object Object]
```

After changing to a different account, it works.

**Comment by obujor** [comment]
There are some issues with saving/opening documents containing time in the version when using existDB backend. For now you can disable existDb as main backend by setting `existIsMainBackend` to `false` in `lime-server/documentsdb/config`. This is an issue of `lime-server`, I created a [new issue](https://github.com/cirsfid-unibo/lime-server/issues/8) there and I'm closing this one.
