### ISSUE TITLE
Server node url at config.json getting ignored

### ISSUE THREAD

**Issue by eltorre** [cirsfid-unibo/lime#71]
I updated ```config.json``` as follows

```
{
    "languages": [{"name":"akoma3.0"}],
    "fieldsDefaults": {
        "docLocale": "it"
    },
    "server": {
        "node": "http://test-server.com:9548"
    }
}
```

When, from another computer in the network I go to test-server.com, LIME loads, but any action (logging in, creating an account) fails. The console has a message stating that it tries to communicate with localhost:9006 (the default value).

**Comment by obujor** [comment]
The config is not ignored, you have to run `sencha app refresh` every time you change the configuration in config.json or in languagesPlugin/akoma3.0 files.

**Comment by dtr5** [comment]
Can you please update https://github.com/cirsfid-unibo/lime/blob/master/docs/Installation.md to reflect this?

**Comment by obujor** [comment]
Yes, I'll update the documentation because `Installation.md` is for LIME 2.0 and not for LIME 2.1. However `sencha app refresh` is used in development within the source code and not at installation.

**Comment by obujor** [comment]
@dtr5 You can see the updated documentation [here](https://github.com/cirsfid-unibo/lime/tree/master/docs) especially the [development](https://github.com/cirsfid-unibo/lime/blob/master/docs/Development.md) one.
