### ISSUE TITLE
Saving a new expression botches metadata

### ISSUE THREAD

**Issue by eltorre** [cirsfid-unibo/lime#73]
When a document is open, save-as is selected, a new Version is created, and a new expression is saved, the old document gets its version metadata field updated. This means that the old document URI and Path do not match.

**Comment by obujor** [comment]
This behavior is not expected, I have to investigate more. However the URI and the path don't have necessarily to match because they are two different concepts: URI is logical, the path is physical. The path can change depending on project/requirements i.e. you can have a path "/myfiles/file.xml".
