### ISSUE TITLE
Differences viewer does not work

### ISSUE THREAD

**Issue by eltorre** [cirsfid-unibo/lime#74]
When two expressions of the same document with changes are visualized using either Differences viewer, the output is:
* No modifies (sic) between these versions
* The document nodes get misaligned in the viewer.

**Comment by obujor** [comment]
The Differences viewer uses AkomaNtoso metadata to show the differences between two versions. In order to use it you have to do legal analysis of the document  (contact @palmirani for this) and mark the modifications which will produce the correct metadata used by the diff.
