### ISSUE TITLE
npm install fails at libxmljs-mt@0.18.0 

### ISSUE THREAD

**Issue by HagayRatzabi** [cirsfid-unibo/lime#75]
Hi guys!

After installing @ cloning the project, when I do '**npm install**' it fails in  **libxmljs-mt@0.18.0**
It has a bug in[ node libs](https://www.google.com/search?q=libxmljs-mt%400.18.0+install%3A+%60node-gyp+rebuild%60&rlz=1C1GCEB_enIL847IL847&oq=libxmljs-mt%400.18.0+install%3A+%60node-gyp+rebuild%60&aqs=chrome..69i57j69i59.543j0j7&sourceid=chrome&ie=UTF-8), or [here](https://github.com/albanm/node-libxslt/issues/68) buy I didn't undersatnd what I supposed to do to fix it.

If any one can help, can can be useful.
Thanks!

**This is how it looks like:**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs-mt@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs-mt@0.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by obujor** [comment]
Hi, could you give more details about the system (at least OS and CPU architecture) where you're trying to install?

In order to install this package (libxmljs) you have to install build-essential tools for your OS.

BTW this is more related to lime-server not this repository.

**Comment by HagayRatzabi** [comment]
Thanks, move thi issue to lime-server.
